---
# tasks/suse/install_dependencies.yml

- name: Ensure required packages are installed (SUSE)
  ansible.builtin.zypper:
    name:
      - curl
      - ca-certificates
      - gnupg
      - lsb-release
    state: present

- name: Add Kubernetes repository key
  ansible.builtin.rpm_key:
    key: "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
    state: present

- name: Add Kubernetes repository
  ansible.builtin.zypper_repository:
    name: kubernetes
    description: Kubernetes Repository
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-suse-{{ ansible_distribution_major_version }}-x86_64"
    enabled: true
    autorefresh: true
    gpgcheck: true
    gpgkey:
      - "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"

- name: Refresh zypper repositories
  ansible.builtin.command:
    cmd: zypper refresh
  changed_when: false  # Prevents unnecessary changes

- name: Install Kubernetes packages
  ansible.builtin.zypper:
    name:
      - kubelet-{{ kubernetes_version }}
      - kubeadm-{{ kubernetes_version }}
      - kubectl-{{ kubernetes_version }}
    state: present
    allow_downgrade: true
    update_cache: true

- name: Install firewalld
  ansible.builtin.zypper:
    name: firewalld
    state: present

- name: Enable and start firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started

- name: Open necessary ports for Kubernetes
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop:
    - ssh
    - http
    - https
    # Add other necessary services/ports as needed

- name: Ensure swap is disabled (SUSE)
  ansible.builtin.command:
    cmd: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Ensure swap is disabled in /etc/fstab (SUSE)
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    replace: '#\1'
