# molecule/default/molecule.yml
---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: localhost
    address: 127.0.0.1
    managed: False  # Prevents Molecule from trying to manage instance creation/deletion
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - dependency
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: ansible

