---
# tasks/arch/install_dependencies.yml

- name: Validate supported architecture
  ansible.builtin.fail:
    msg: "Architecture '{{ ansible_architecture }}' is not supported by this role."
  when: ansible_architecture not in supported_architectures

# Add any architecture-specific dependency installations here.
# For example, if arm64 requires additional repositories or packages.

- name: Install additional packages for arm64
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - some-arm64-specific-package  # Replace with actual package names if needed
  when: ansible_architecture == "arm64"
  