---
# tasks/redhat/install_dependencies.yml

- name: Ensure required packages are installed (RedHat)
  ansible.builtin.yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Kubernetes YUM repository
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes Repository
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-{{ ansible_distribution_major_version }}-x86_64"
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Disable SELinux (if necessary)
  ansible.posix.selinux:
    state: disabled
  when: ansible_selinux.status == "enabled"

- name: Set SELinux to permissive mode
  ansible.builtin.command: setenforce 0
  when:
    - ansible_selinux.status == "enabled"
    - ansible_selinux.mode != "permissive"

- name: Install firewalld
  ansible.builtin.yum:
    name: firewalld
    state: present

- name: Enable and start firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started

- name: Open necessary ports for Kubernetes
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop:
    - ssh
    - http
    - https
    # Add other necessary services/ports as needed

- name: Ensure swap is disabled (RedHat)
  ansible.builtin.command:
    cmd: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Ensure swap is disabled in /etc/fstab (RedHat)
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    replace: '#\1'
