---
# tasks/common/install_kubernetes.yml

- name: Install Kubernetes packages based on architecture
  package:
    name:
      - "{{ arch_packages[ansible_architecture].kubelet }}"
      - "{{ arch_packages[ansible_architecture].kubeadm }}"
      - "{{ arch_packages[ansible_architecture].kubectl }}"
    state: present
    allow_downgrade: yes
    update_cache: yes
  become: yes

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started
  become: yes

- name: Disable swap
  command: swapoff -a
  become: yes
  ignore_errors: yes

- name: Ensure swap is disabled in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    replace: '#\1'
  become: yes

- name: Initialize Kubernetes cluster
  command: kubeadm init --kubernetes-version {{ kubernetes_version }} --pod-network-cidr={{ pod_network_cidr }}
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init
  become: yes
  ignore_errors: yes

- name: Create .kube directory for admin user
  file:
    path: /home/{{ k8s_admin_user }}/.kube
    state: directory
    owner: "{{ k8s_admin_user }}"
    group: "{{ k8s_admin_user }}"
    mode: '0755'
  become: yes
  when: kubeadm_init.rc == 0

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ k8s_admin_user }}/.kube/config
    owner: "{{ k8s_admin_user }}"
    group: "{{ k8s_admin_user }}"
    mode: '0644'
  become: yes
  when: kubeadm_init.rc == 0
