---
on: 
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secret.AUTOMATION_PAT }}
      - name: 'Ansible Lint'
        uses: ansible/ansible-lint@v24.9.2
