---
# .github/workflows/checkov.yml
name: 'Checkov Scan'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkov_scan:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v2

    - name: 'Run Checkov on Ansible'
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: "."  # Root directory or specify path to Ansible playbooks
        skip_path: "molecule/,.github/"  # Optional: Use to skip irrelevant checks (e.g., AWS-specific)
